class SpecialTokens:

    CHAPTER_NAME_START = '<CHAPTER_NAME_START>'
    CHAPTER_NAME_END = '<CHAPTER_NAME_END>'
    HEADING_START = '<HEADING_START>'
    HEADING_END = '<HEADING_END>'
    PARAGRAPH_START = '<PARA_START>'
    PARAGRAPH_END = '<PARA_END>'
    END = '<END>'
    UNKNOWN = '<UNK>'